#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t glade"

$L " ██████╗ ██╗      █████╗ ██████╗ ███████╗";
$L "██╔════╝ ██║     ██╔══██╗██╔══██╗██╔════╝";
$L "██║  ███╗██║     ███████║██║  ██║█████╗  ";
$L "██║   ██║██║     ██╔══██║██║  ██║██╔══╝  ";
$L "╚██████╔╝███████╗██║  ██║██████╔╝███████╗";
$L " ╚═════╝ ╚══════╝╚═╝  ╚═╝╚═════╝ ╚══════╝";
$L "Welcome to Android `getprop ro.build.version.release` / Glade-`getprop ro.glade.version`";
